
const artikelData = [
  { artikelnummer: "1000", name: "Versandkosten", einheit: "6", preis: 14.9, vielfaches: 6 },
  { artikelnummer: "1002", name: "Eichhörnchen Sterne gold", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1003", name: "Squirrel Stars burnt orange", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1004", name: "Squirrel Bubble magenta", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1005", name: "Squirrel Bubble violet", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1006", name: "Squirrel Stars bubblegum", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1007", name: "Petroltanne neonorange", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1008", name: "Tinted Glückwünsche Gelb", einheit: "6", preis: 3.0, vielfaches: 6 },
  { artikelnummer: "1009", name: "Stabkerze 210x21 Marmoreffekt", einheit: "6", preis: 1.25, vielfaches: 6 },
  { artikelnummer: "1010", name: "Lama Grande * Amaya", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1011", name: "Lama Grande * Ariana", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1012", name: "Lama Grande * Camila", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1013", name: "Lama Grande * Luciana", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1014", name: "Lama Grande * Miren", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1015", name: "Lama Grande * Valeria", einheit: "6", preis: 3.25, vielfaches: 6 },
  { artikelnummer: "1016", name: "Lama Mini * Huaraz", einheit: "6", preis: 2.25, vielfaches: 6 },
  { artikelnummer: "1017", name: "Lama Medio * Alejandro", einheit: "6", preis: 2.75, vielfaches: 6 },
  { artikelnummer: "1018", name: "Lama Medio * Alvaro", einheit: "6", preis: 2.75, vielfaches: 6 },
  { artikelnummer: "1019", name: "Lama Medio * Amaru", einheit: "6", preis: 2.75, vielfaches: 6 },
  { artikelnummer: "1020", name: "Stabkerze 210x21 Reisseffekt", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1021", name: "Glaskugel grau matt/silber", einheit: "6", preis: 1.25, vielfaches: 6 },
  { artikelnummer: "1022", name: "Glaskugel petrol matt/gold", einheit: "6", preis: 1.25, vielfaches: 6 },
  { artikelnummer: "1023", name: "Glaskugel bubblegum/weiß glanz", einheit: "6", preis: 1.25, vielfaches: 6 },
  { artikelnummer: "1024", name: "Glaskugel bubblegum/weiß matt", einheit: "6", preis: 1.25, vielfaches: 6 },
  { artikelnummer: "1025", name: "Stabkerze 210x21 Wunschtext Bubblegum", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1026", name: "Stabkerze 210x21 Wunschtext Magenta", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1027", name: "Stabkerze 210x21 Wunschtext Lila", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1028", name: "Stabkerze 210x21 Wunschtext Orange", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1029", name: "Stabkerze 210x21 Wunschtext Mint", einheit: "6", preis: 1.75, vielfaches: 6 },
  { artikelnummer: "1030", name: "Stabkerze 210x21 Wunschtext Petrol", einheit: "6", preis: 1.75, vielfaches: 6 }
];
